# Generated by Django 4.0.3 on 2022-03-09 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiking_method', models.CharField(max_length=20)),
                ('has_reported', models.CharField(max_length=3)),
                ('incident_place', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('latitude', models.CharField(blank=True, default=None, max_length=200)),
                ('longitude', models.CharField(blank=True, default=None, max_length=200)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('substance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='substance.substance')),
            ],
        ),
    ]
